#ifndef CFS_API_READER_H
#define CFS_API_READER_H

/* Generated by flatcc 0.6.0-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef COMMON_READER_H
#include "common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct cFS_API_cFETime_table *cFS_API_cFETime_table_t;
typedef struct cFS_API_cFETime_table *cFS_API_cFETime_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_cFETime_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_cFETime_mutable_vec_t;
typedef const struct cFS_API_RunLoop_table *cFS_API_RunLoop_table_t;
typedef struct cFS_API_RunLoop_table *cFS_API_RunLoop_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_RunLoop_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_RunLoop_mutable_vec_t;
typedef const struct cFS_API_PerfLogAdd_table *cFS_API_PerfLogAdd_table_t;
typedef struct cFS_API_PerfLogAdd_table *cFS_API_PerfLogAdd_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_PerfLogAdd_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_PerfLogAdd_mutable_vec_t;
typedef const struct cFS_API_RegisterApp_table *cFS_API_RegisterApp_table_t;
typedef struct cFS_API_RegisterApp_table *cFS_API_RegisterApp_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_RegisterApp_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_RegisterApp_mutable_vec_t;
typedef const struct cFS_API_ExitApp_table *cFS_API_ExitApp_table_t;
typedef struct cFS_API_ExitApp_table *cFS_API_ExitApp_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_ExitApp_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_ExitApp_mutable_vec_t;
typedef const struct cFS_API_SendEvent_table *cFS_API_SendEvent_table_t;
typedef struct cFS_API_SendEvent_table *cFS_API_SendEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_SendEvent_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_SendEvent_mutable_vec_t;
typedef const struct cFS_API_SendEventWithAppID_table *cFS_API_SendEventWithAppID_table_t;
typedef struct cFS_API_SendEventWithAppID_table *cFS_API_SendEventWithAppID_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_SendEventWithAppID_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_SendEventWithAppID_mutable_vec_t;
typedef const struct cFS_API_SendTimedEvent_table *cFS_API_SendTimedEvent_table_t;
typedef struct cFS_API_SendTimedEvent_table *cFS_API_SendTimedEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_SendTimedEvent_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_SendTimedEvent_mutable_vec_t;
typedef const struct cFS_API_Filter_table *cFS_API_Filter_table_t;
typedef struct cFS_API_Filter_table *cFS_API_Filter_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_Filter_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_Filter_mutable_vec_t;
typedef const struct cFS_API_Register_table *cFS_API_Register_table_t;
typedef struct cFS_API_Register_table *cFS_API_Register_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_Register_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_Register_mutable_vec_t;
typedef const struct cFS_API_Unregister_table *cFS_API_Unregister_table_t;
typedef struct cFS_API_Unregister_table *cFS_API_Unregister_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_Unregister_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_Unregister_mutable_vec_t;
typedef const struct cFS_API_ResetFilter_table *cFS_API_ResetFilter_table_t;
typedef struct cFS_API_ResetFilter_table *cFS_API_ResetFilter_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_ResetFilter_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_ResetFilter_mutable_vec_t;
typedef const struct cFS_API_ResetAllFilters_table *cFS_API_ResetAllFilters_table_t;
typedef struct cFS_API_ResetAllFilters_table *cFS_API_ResetAllFilters_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_ResetAllFilters_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_ResetAllFilters_mutable_vec_t;
typedef const struct cFS_API_TIME_GetTime_table *cFS_API_TIME_GetTime_table_t;
typedef struct cFS_API_TIME_GetTime_table *cFS_API_TIME_GetTime_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetTime_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetTime_mutable_vec_t;
typedef const struct cFS_API_TIME_GetTAI_table *cFS_API_TIME_GetTAI_table_t;
typedef struct cFS_API_TIME_GetTAI_table *cFS_API_TIME_GetTAI_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetTAI_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetTAI_mutable_vec_t;
typedef const struct cFS_API_TIME_GetUTC_table *cFS_API_TIME_GetUTC_table_t;
typedef struct cFS_API_TIME_GetUTC_table *cFS_API_TIME_GetUTC_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetUTC_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetUTC_mutable_vec_t;
typedef const struct cFS_API_TIME_MET2SCTime_table *cFS_API_TIME_MET2SCTime_table_t;
typedef struct cFS_API_TIME_MET2SCTime_table *cFS_API_TIME_MET2SCTime_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_MET2SCTime_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_MET2SCTime_mutable_vec_t;
typedef const struct cFS_API_TIME_GetSTCF_table *cFS_API_TIME_GetSTCF_table_t;
typedef struct cFS_API_TIME_GetSTCF_table *cFS_API_TIME_GetSTCF_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetSTCF_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetSTCF_mutable_vec_t;
typedef const struct cFS_API_TIME_GetMET_table *cFS_API_TIME_GetMET_table_t;
typedef struct cFS_API_TIME_GetMET_table *cFS_API_TIME_GetMET_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetMET_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetMET_mutable_vec_t;
typedef const struct cFS_API_TIME_GetMETseconds_table *cFS_API_TIME_GetMETseconds_table_t;
typedef struct cFS_API_TIME_GetMETseconds_table *cFS_API_TIME_GetMETseconds_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetMETseconds_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetMETseconds_mutable_vec_t;
typedef const struct cFS_API_TIME_GetMETsubsecs_table *cFS_API_TIME_GetMETsubsecs_table_t;
typedef struct cFS_API_TIME_GetMETsubsecs_table *cFS_API_TIME_GetMETsubsecs_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetMETsubsecs_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetMETsubsecs_mutable_vec_t;
typedef const struct cFS_API_TIME_GetLeapSeconds_table *cFS_API_TIME_GetLeapSeconds_table_t;
typedef struct cFS_API_TIME_GetLeapSeconds_table *cFS_API_TIME_GetLeapSeconds_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetLeapSeconds_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetLeapSeconds_mutable_vec_t;
typedef const struct cFS_API_TIME_GetClockState_table *cFS_API_TIME_GetClockState_table_t;
typedef struct cFS_API_TIME_GetClockState_table *cFS_API_TIME_GetClockState_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetClockState_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetClockState_mutable_vec_t;
typedef const struct cFS_API_TIME_GetClockInfo_table *cFS_API_TIME_GetClockInfo_table_t;
typedef struct cFS_API_TIME_GetClockInfo_table *cFS_API_TIME_GetClockInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_TIME_GetClockInfo_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_TIME_GetClockInfo_mutable_vec_t;
typedef const struct cFS_API_RemoteCall_table *cFS_API_RemoteCall_table_t;
typedef struct cFS_API_RemoteCall_table *cFS_API_RemoteCall_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_API_RemoteCall_vec_t;
typedef flatbuffers_uoffset_t *cFS_API_RemoteCall_mutable_vec_t;
#ifndef cFS_API_cFETime_identifier
#define cFS_API_cFETime_identifier flatbuffers_identifier
#endif
#define cFS_API_cFETime_type_hash ((flatbuffers_thash_t)0x7ccd98e5)
#define cFS_API_cFETime_type_identifier "\xe5\x98\xcd\x7c"
#ifndef cFS_API_RunLoop_identifier
#define cFS_API_RunLoop_identifier flatbuffers_identifier
#endif
#define cFS_API_RunLoop_type_hash ((flatbuffers_thash_t)0x88f85c1f)
#define cFS_API_RunLoop_type_identifier "\x1f\x5c\xf8\x88"
#ifndef cFS_API_PerfLogAdd_identifier
#define cFS_API_PerfLogAdd_identifier flatbuffers_identifier
#endif
#define cFS_API_PerfLogAdd_type_hash ((flatbuffers_thash_t)0xbf6aca52)
#define cFS_API_PerfLogAdd_type_identifier "\x52\xca\x6a\xbf"
#ifndef cFS_API_RegisterApp_identifier
#define cFS_API_RegisterApp_identifier flatbuffers_identifier
#endif
#define cFS_API_RegisterApp_type_hash ((flatbuffers_thash_t)0xde67bf14)
#define cFS_API_RegisterApp_type_identifier "\x14\xbf\x67\xde"
#ifndef cFS_API_ExitApp_identifier
#define cFS_API_ExitApp_identifier flatbuffers_identifier
#endif
#define cFS_API_ExitApp_type_hash ((flatbuffers_thash_t)0xa34023f7)
#define cFS_API_ExitApp_type_identifier "\xf7\x23\x40\xa3"
#ifndef cFS_API_SendEvent_identifier
#define cFS_API_SendEvent_identifier flatbuffers_identifier
#endif
#define cFS_API_SendEvent_type_hash ((flatbuffers_thash_t)0x1cc69526)
#define cFS_API_SendEvent_type_identifier "\x26\x95\xc6\x1c"
#ifndef cFS_API_SendEventWithAppID_identifier
#define cFS_API_SendEventWithAppID_identifier flatbuffers_identifier
#endif
#define cFS_API_SendEventWithAppID_type_hash ((flatbuffers_thash_t)0x8f625ab4)
#define cFS_API_SendEventWithAppID_type_identifier "\xb4\x5a\x62\x8f"
#ifndef cFS_API_SendTimedEvent_identifier
#define cFS_API_SendTimedEvent_identifier flatbuffers_identifier
#endif
#define cFS_API_SendTimedEvent_type_hash ((flatbuffers_thash_t)0xd275ed77)
#define cFS_API_SendTimedEvent_type_identifier "\x77\xed\x75\xd2"
#ifndef cFS_API_Filter_identifier
#define cFS_API_Filter_identifier flatbuffers_identifier
#endif
#define cFS_API_Filter_type_hash ((flatbuffers_thash_t)0xb040d3b6)
#define cFS_API_Filter_type_identifier "\xb6\xd3\x40\xb0"
#ifndef cFS_API_Register_identifier
#define cFS_API_Register_identifier flatbuffers_identifier
#endif
#define cFS_API_Register_type_hash ((flatbuffers_thash_t)0xc6d7205d)
#define cFS_API_Register_type_identifier "\x5d\x20\xd7\xc6"
#ifndef cFS_API_Unregister_identifier
#define cFS_API_Unregister_identifier flatbuffers_identifier
#endif
#define cFS_API_Unregister_type_hash ((flatbuffers_thash_t)0xe90b008a)
#define cFS_API_Unregister_type_identifier "\x8a\x00\x0b\xe9"
#ifndef cFS_API_ResetFilter_identifier
#define cFS_API_ResetFilter_identifier flatbuffers_identifier
#endif
#define cFS_API_ResetFilter_type_hash ((flatbuffers_thash_t)0x1ebbcbd)
#define cFS_API_ResetFilter_type_identifier "\xbd\xbc\xeb\x01"
#ifndef cFS_API_ResetAllFilters_identifier
#define cFS_API_ResetAllFilters_identifier flatbuffers_identifier
#endif
#define cFS_API_ResetAllFilters_type_hash ((flatbuffers_thash_t)0xbb752829)
#define cFS_API_ResetAllFilters_type_identifier "\x29\x28\x75\xbb"
#ifndef cFS_API_TIME_GetTime_identifier
#define cFS_API_TIME_GetTime_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetTime_type_hash ((flatbuffers_thash_t)0x8c1826ab)
#define cFS_API_TIME_GetTime_type_identifier "\xab\x26\x18\x8c"
#ifndef cFS_API_TIME_GetTAI_identifier
#define cFS_API_TIME_GetTAI_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetTAI_type_hash ((flatbuffers_thash_t)0xfdc7318)
#define cFS_API_TIME_GetTAI_type_identifier "\x18\x73\xdc\x0f"
#ifndef cFS_API_TIME_GetUTC_identifier
#define cFS_API_TIME_GetUTC_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetUTC_type_hash ((flatbuffers_thash_t)0xe6de5928)
#define cFS_API_TIME_GetUTC_type_identifier "\x28\x59\xde\xe6"
#ifndef cFS_API_TIME_MET2SCTime_identifier
#define cFS_API_TIME_MET2SCTime_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_MET2SCTime_type_hash ((flatbuffers_thash_t)0xc7cfda65)
#define cFS_API_TIME_MET2SCTime_type_identifier "\x65\xda\xcf\xc7"
#ifndef cFS_API_TIME_GetSTCF_identifier
#define cFS_API_TIME_GetSTCF_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetSTCF_type_hash ((flatbuffers_thash_t)0x2ca2cd14)
#define cFS_API_TIME_GetSTCF_type_identifier "\x14\xcd\xa2\x2c"
#ifndef cFS_API_TIME_GetMET_identifier
#define cFS_API_TIME_GetMET_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetMET_type_hash ((flatbuffers_thash_t)0x90d658dc)
#define cFS_API_TIME_GetMET_type_identifier "\xdc\x58\xd6\x90"
#ifndef cFS_API_TIME_GetMETseconds_identifier
#define cFS_API_TIME_GetMETseconds_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetMETseconds_type_hash ((flatbuffers_thash_t)0x9b28a1e1)
#define cFS_API_TIME_GetMETseconds_type_identifier "\xe1\xa1\x28\x9b"
#ifndef cFS_API_TIME_GetMETsubsecs_identifier
#define cFS_API_TIME_GetMETsubsecs_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetMETsubsecs_type_hash ((flatbuffers_thash_t)0x14a421e4)
#define cFS_API_TIME_GetMETsubsecs_type_identifier "\xe4\x21\xa4\x14"
#ifndef cFS_API_TIME_GetLeapSeconds_identifier
#define cFS_API_TIME_GetLeapSeconds_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetLeapSeconds_type_hash ((flatbuffers_thash_t)0x229ee259)
#define cFS_API_TIME_GetLeapSeconds_type_identifier "\x59\xe2\x9e\x22"
#ifndef cFS_API_TIME_GetClockState_identifier
#define cFS_API_TIME_GetClockState_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetClockState_type_hash ((flatbuffers_thash_t)0x792df559)
#define cFS_API_TIME_GetClockState_type_identifier "\x59\xf5\x2d\x79"
#ifndef cFS_API_TIME_GetClockInfo_identifier
#define cFS_API_TIME_GetClockInfo_identifier flatbuffers_identifier
#endif
#define cFS_API_TIME_GetClockInfo_type_hash ((flatbuffers_thash_t)0x3b5bcd8)
#define cFS_API_TIME_GetClockInfo_type_identifier "\xd8\xbc\xb5\x03"
#ifndef cFS_API_RemoteCall_identifier
#define cFS_API_RemoteCall_identifier flatbuffers_identifier
#endif
#define cFS_API_RemoteCall_type_hash ((flatbuffers_thash_t)0x249b70b6)
#define cFS_API_RemoteCall_type_identifier "\xb6\x70\x9b\x24"



/** ///////////////////////////////////////////////// */
struct cFS_API_cFETime_table { uint8_t unused__; };

static inline size_t cFS_API_cFETime_vec_len(cFS_API_cFETime_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_cFETime_table_t cFS_API_cFETime_vec_at(cFS_API_cFETime_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_cFETime_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_cFETime)

__flatbuffers_define_scalar_field(0, cFS_API_cFETime, Seconds, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, cFS_API_cFETime, Subseconds, flatbuffers_uint32, uint32_t, UINT32_C(0))

/** ///////////////////////////////////////////////// */
struct cFS_API_RunLoop_table { uint8_t unused__; };

static inline size_t cFS_API_RunLoop_vec_len(cFS_API_RunLoop_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_RunLoop_table_t cFS_API_RunLoop_vec_at(cFS_API_RunLoop_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_RunLoop_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_RunLoop)

__flatbuffers_define_scalar_field(0, cFS_API_RunLoop, ExitStatus, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct cFS_API_PerfLogAdd_table { uint8_t unused__; };

static inline size_t cFS_API_PerfLogAdd_vec_len(cFS_API_PerfLogAdd_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_PerfLogAdd_table_t cFS_API_PerfLogAdd_vec_at(cFS_API_PerfLogAdd_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_PerfLogAdd_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_PerfLogAdd)

__flatbuffers_define_scalar_field(0, cFS_API_PerfLogAdd, Marker, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, cFS_API_PerfLogAdd, EntryExit, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct cFS_API_RegisterApp_table { uint8_t unused__; };

static inline size_t cFS_API_RegisterApp_vec_len(cFS_API_RegisterApp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_RegisterApp_table_t cFS_API_RegisterApp_vec_at(cFS_API_RegisterApp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_RegisterApp_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_RegisterApp)


struct cFS_API_ExitApp_table { uint8_t unused__; };

static inline size_t cFS_API_ExitApp_vec_len(cFS_API_ExitApp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_ExitApp_table_t cFS_API_ExitApp_vec_at(cFS_API_ExitApp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_ExitApp_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_ExitApp)

__flatbuffers_define_scalar_field(0, cFS_API_ExitApp, ExitStatus, flatbuffers_uint32, uint32_t, UINT32_C(0))

/** ///////////////////////////////////////////////// */
struct cFS_API_SendEvent_table { uint8_t unused__; };

static inline size_t cFS_API_SendEvent_vec_len(cFS_API_SendEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_SendEvent_table_t cFS_API_SendEvent_vec_at(cFS_API_SendEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_SendEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_SendEvent)

__flatbuffers_define_scalar_field(0, cFS_API_SendEvent, EventID, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, cFS_API_SendEvent, EventType, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(2, cFS_API_SendEvent, Spec, 0)

struct cFS_API_SendEventWithAppID_table { uint8_t unused__; };

static inline size_t cFS_API_SendEventWithAppID_vec_len(cFS_API_SendEventWithAppID_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_SendEventWithAppID_table_t cFS_API_SendEventWithAppID_vec_at(cFS_API_SendEventWithAppID_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_SendEventWithAppID_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_SendEventWithAppID)

__flatbuffers_define_scalar_field(0, cFS_API_SendEventWithAppID, EventID, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, cFS_API_SendEventWithAppID, EventType, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, cFS_API_SendEventWithAppID, AppID, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(3, cFS_API_SendEventWithAppID, Spec, 0)

struct cFS_API_SendTimedEvent_table { uint8_t unused__; };

static inline size_t cFS_API_SendTimedEvent_vec_len(cFS_API_SendTimedEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_SendTimedEvent_table_t cFS_API_SendTimedEvent_vec_at(cFS_API_SendTimedEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_SendTimedEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_SendTimedEvent)

__flatbuffers_define_table_field(0, cFS_API_SendTimedEvent, Time, cFS_API_cFETime_table_t, 0)
__flatbuffers_define_scalar_field(1, cFS_API_SendTimedEvent, EventID, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, cFS_API_SendTimedEvent, EventType, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(3, cFS_API_SendTimedEvent, Spec, 0)

struct cFS_API_Filter_table { uint8_t unused__; };

static inline size_t cFS_API_Filter_vec_len(cFS_API_Filter_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_Filter_table_t cFS_API_Filter_vec_at(cFS_API_Filter_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_Filter_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_Filter)

__flatbuffers_define_scalar_field(0, cFS_API_Filter, EventID, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, cFS_API_Filter, Mask, flatbuffers_uint16, uint16_t, UINT16_C(0))

struct cFS_API_Register_table { uint8_t unused__; };

static inline size_t cFS_API_Register_vec_len(cFS_API_Register_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_Register_table_t cFS_API_Register_vec_at(cFS_API_Register_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_Register_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_Register)

__flatbuffers_define_vector_field(0, cFS_API_Register, Filters, cFS_API_Filter_vec_t, 0)
__flatbuffers_define_scalar_field(1, cFS_API_Register, NumFilteredEvents, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, cFS_API_Register, FilterScheme, flatbuffers_uint16, uint16_t, UINT16_C(0))

struct cFS_API_Unregister_table { uint8_t unused__; };

static inline size_t cFS_API_Unregister_vec_len(cFS_API_Unregister_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_Unregister_table_t cFS_API_Unregister_vec_at(cFS_API_Unregister_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_Unregister_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_Unregister)


struct cFS_API_ResetFilter_table { uint8_t unused__; };

static inline size_t cFS_API_ResetFilter_vec_len(cFS_API_ResetFilter_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_ResetFilter_table_t cFS_API_ResetFilter_vec_at(cFS_API_ResetFilter_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_ResetFilter_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_ResetFilter)

__flatbuffers_define_scalar_field(0, cFS_API_ResetFilter, EventID, flatbuffers_int16, int16_t, INT16_C(0))

struct cFS_API_ResetAllFilters_table { uint8_t unused__; };

static inline size_t cFS_API_ResetAllFilters_vec_len(cFS_API_ResetAllFilters_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_ResetAllFilters_table_t cFS_API_ResetAllFilters_vec_at(cFS_API_ResetAllFilters_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_ResetAllFilters_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_ResetAllFilters)


/** /////////////////////////////////////////////////
 * /////////////////////////////////////////////////
 * ///////////////////////////////////////////////// */
struct cFS_API_TIME_GetTime_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetTime_vec_len(cFS_API_TIME_GetTime_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetTime_table_t cFS_API_TIME_GetTime_vec_at(cFS_API_TIME_GetTime_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetTime_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetTime)


struct cFS_API_TIME_GetTAI_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetTAI_vec_len(cFS_API_TIME_GetTAI_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetTAI_table_t cFS_API_TIME_GetTAI_vec_at(cFS_API_TIME_GetTAI_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetTAI_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetTAI)


struct cFS_API_TIME_GetUTC_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetUTC_vec_len(cFS_API_TIME_GetUTC_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetUTC_table_t cFS_API_TIME_GetUTC_vec_at(cFS_API_TIME_GetUTC_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetUTC_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetUTC)


struct cFS_API_TIME_MET2SCTime_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_MET2SCTime_vec_len(cFS_API_TIME_MET2SCTime_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_MET2SCTime_table_t cFS_API_TIME_MET2SCTime_vec_at(cFS_API_TIME_MET2SCTime_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_MET2SCTime_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_MET2SCTime)

__flatbuffers_define_table_field(0, cFS_API_TIME_MET2SCTime, METTime, cFS_API_cFETime_table_t, 0)

struct cFS_API_TIME_GetSTCF_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetSTCF_vec_len(cFS_API_TIME_GetSTCF_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetSTCF_table_t cFS_API_TIME_GetSTCF_vec_at(cFS_API_TIME_GetSTCF_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetSTCF_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetSTCF)


struct cFS_API_TIME_GetMET_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetMET_vec_len(cFS_API_TIME_GetMET_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetMET_table_t cFS_API_TIME_GetMET_vec_at(cFS_API_TIME_GetMET_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetMET_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetMET)


struct cFS_API_TIME_GetMETseconds_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetMETseconds_vec_len(cFS_API_TIME_GetMETseconds_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetMETseconds_table_t cFS_API_TIME_GetMETseconds_vec_at(cFS_API_TIME_GetMETseconds_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetMETseconds_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetMETseconds)


struct cFS_API_TIME_GetMETsubsecs_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetMETsubsecs_vec_len(cFS_API_TIME_GetMETsubsecs_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetMETsubsecs_table_t cFS_API_TIME_GetMETsubsecs_vec_at(cFS_API_TIME_GetMETsubsecs_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetMETsubsecs_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetMETsubsecs)


struct cFS_API_TIME_GetLeapSeconds_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetLeapSeconds_vec_len(cFS_API_TIME_GetLeapSeconds_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetLeapSeconds_table_t cFS_API_TIME_GetLeapSeconds_vec_at(cFS_API_TIME_GetLeapSeconds_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetLeapSeconds_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetLeapSeconds)


struct cFS_API_TIME_GetClockState_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetClockState_vec_len(cFS_API_TIME_GetClockState_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetClockState_table_t cFS_API_TIME_GetClockState_vec_at(cFS_API_TIME_GetClockState_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetClockState_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetClockState)


struct cFS_API_TIME_GetClockInfo_table { uint8_t unused__; };

static inline size_t cFS_API_TIME_GetClockInfo_vec_len(cFS_API_TIME_GetClockInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_TIME_GetClockInfo_table_t cFS_API_TIME_GetClockInfo_vec_at(cFS_API_TIME_GetClockInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_TIME_GetClockInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_TIME_GetClockInfo)

/** /////////////////////////////////////////////////
 * ///////////////////////////////////////////////// */
typedef uint8_t cFS_API_Function_union_type_t;
__flatbuffers_define_integer_type(cFS_API_Function, cFS_API_Function_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, cFS_API_Function)
#define cFS_API_Function_NONE ((cFS_API_Function_union_type_t)UINT8_C(0))
#define cFS_API_Function_RunLoop ((cFS_API_Function_union_type_t)UINT8_C(1))
#define cFS_API_Function_PerfLogAdd ((cFS_API_Function_union_type_t)UINT8_C(2))
#define cFS_API_Function_RegisterApp ((cFS_API_Function_union_type_t)UINT8_C(3))
#define cFS_API_Function_ExitApp ((cFS_API_Function_union_type_t)UINT8_C(4))
#define cFS_API_Function_Register ((cFS_API_Function_union_type_t)UINT8_C(5))
#define cFS_API_Function_Unregister ((cFS_API_Function_union_type_t)UINT8_C(6))
#define cFS_API_Function_SendEvent ((cFS_API_Function_union_type_t)UINT8_C(7))
#define cFS_API_Function_SendEventWithAppID ((cFS_API_Function_union_type_t)UINT8_C(8))
#define cFS_API_Function_SendTimedEvent ((cFS_API_Function_union_type_t)UINT8_C(9))
#define cFS_API_Function_ResetFilter ((cFS_API_Function_union_type_t)UINT8_C(10))
#define cFS_API_Function_ResetAllFilters ((cFS_API_Function_union_type_t)UINT8_C(11))
#define cFS_API_Function_TIME_GetTime ((cFS_API_Function_union_type_t)UINT8_C(12))
#define cFS_API_Function_TIME_GetTAI ((cFS_API_Function_union_type_t)UINT8_C(13))
#define cFS_API_Function_TIME_GetUTC ((cFS_API_Function_union_type_t)UINT8_C(14))
#define cFS_API_Function_TIME_MET2SCTime ((cFS_API_Function_union_type_t)UINT8_C(15))
#define cFS_API_Function_TIME_GetSTCF ((cFS_API_Function_union_type_t)UINT8_C(16))
#define cFS_API_Function_TIME_GetMET ((cFS_API_Function_union_type_t)UINT8_C(17))
#define cFS_API_Function_TIME_GetMETseconds ((cFS_API_Function_union_type_t)UINT8_C(18))
#define cFS_API_Function_TIME_GetMETsubsecs ((cFS_API_Function_union_type_t)UINT8_C(19))
#define cFS_API_Function_TIME_GetLeapSeconds ((cFS_API_Function_union_type_t)UINT8_C(20))
#define cFS_API_Function_TIME_GetClockState ((cFS_API_Function_union_type_t)UINT8_C(21))
#define cFS_API_Function_TIME_GetClockInfo ((cFS_API_Function_union_type_t)UINT8_C(22))

static inline const char *cFS_API_Function_type_name(cFS_API_Function_union_type_t type)
{
    switch (type) {
    case cFS_API_Function_NONE: return "NONE";
    case cFS_API_Function_RunLoop: return "RunLoop";
    case cFS_API_Function_PerfLogAdd: return "PerfLogAdd";
    case cFS_API_Function_RegisterApp: return "RegisterApp";
    case cFS_API_Function_ExitApp: return "ExitApp";
    case cFS_API_Function_Register: return "Register";
    case cFS_API_Function_Unregister: return "Unregister";
    case cFS_API_Function_SendEvent: return "SendEvent";
    case cFS_API_Function_SendEventWithAppID: return "SendEventWithAppID";
    case cFS_API_Function_SendTimedEvent: return "SendTimedEvent";
    case cFS_API_Function_ResetFilter: return "ResetFilter";
    case cFS_API_Function_ResetAllFilters: return "ResetAllFilters";
    case cFS_API_Function_TIME_GetTime: return "TIME_GetTime";
    case cFS_API_Function_TIME_GetTAI: return "TIME_GetTAI";
    case cFS_API_Function_TIME_GetUTC: return "TIME_GetUTC";
    case cFS_API_Function_TIME_MET2SCTime: return "TIME_MET2SCTime";
    case cFS_API_Function_TIME_GetSTCF: return "TIME_GetSTCF";
    case cFS_API_Function_TIME_GetMET: return "TIME_GetMET";
    case cFS_API_Function_TIME_GetMETseconds: return "TIME_GetMETseconds";
    case cFS_API_Function_TIME_GetMETsubsecs: return "TIME_GetMETsubsecs";
    case cFS_API_Function_TIME_GetLeapSeconds: return "TIME_GetLeapSeconds";
    case cFS_API_Function_TIME_GetClockState: return "TIME_GetClockState";
    case cFS_API_Function_TIME_GetClockInfo: return "TIME_GetClockInfo";
    default: return "";
    }
}

static inline int cFS_API_Function_is_known_type(cFS_API_Function_union_type_t type)
{
    switch (type) {
    case cFS_API_Function_NONE: return 1;
    case cFS_API_Function_RunLoop: return 1;
    case cFS_API_Function_PerfLogAdd: return 1;
    case cFS_API_Function_RegisterApp: return 1;
    case cFS_API_Function_ExitApp: return 1;
    case cFS_API_Function_Register: return 1;
    case cFS_API_Function_Unregister: return 1;
    case cFS_API_Function_SendEvent: return 1;
    case cFS_API_Function_SendEventWithAppID: return 1;
    case cFS_API_Function_SendTimedEvent: return 1;
    case cFS_API_Function_ResetFilter: return 1;
    case cFS_API_Function_ResetAllFilters: return 1;
    case cFS_API_Function_TIME_GetTime: return 1;
    case cFS_API_Function_TIME_GetTAI: return 1;
    case cFS_API_Function_TIME_GetUTC: return 1;
    case cFS_API_Function_TIME_MET2SCTime: return 1;
    case cFS_API_Function_TIME_GetSTCF: return 1;
    case cFS_API_Function_TIME_GetMET: return 1;
    case cFS_API_Function_TIME_GetMETseconds: return 1;
    case cFS_API_Function_TIME_GetMETsubsecs: return 1;
    case cFS_API_Function_TIME_GetLeapSeconds: return 1;
    case cFS_API_Function_TIME_GetClockState: return 1;
    case cFS_API_Function_TIME_GetClockInfo: return 1;
    default: return 0;
    }
}


struct cFS_API_RemoteCall_table { uint8_t unused__; };

static inline size_t cFS_API_RemoteCall_vec_len(cFS_API_RemoteCall_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_API_RemoteCall_table_t cFS_API_RemoteCall_vec_at(cFS_API_RemoteCall_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_API_RemoteCall_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_API_RemoteCall)

__flatbuffers_define_union_field(flatbuffers_, 1, cFS_API_RemoteCall, input, cFS_API_Function, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* CFS_API_READER_H */
