#ifndef CFS_RETURN_READER_H
#define CFS_RETURN_READER_H

/* Generated by flatcc 0.6.0-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct cFS_Return_Empty_table *cFS_Return_Empty_table_t;
typedef struct cFS_Return_Empty_table *cFS_Return_Empty_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_Return_Empty_vec_t;
typedef flatbuffers_uoffset_t *cFS_Return_Empty_mutable_vec_t;
typedef const struct cFS_Return_UnInt_table *cFS_Return_UnInt_table_t;
typedef struct cFS_Return_UnInt_table *cFS_Return_UnInt_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_Return_UnInt_vec_t;
typedef flatbuffers_uoffset_t *cFS_Return_UnInt_mutable_vec_t;
typedef const struct cFS_Return_ReturnData_table *cFS_Return_ReturnData_table_t;
typedef struct cFS_Return_ReturnData_table *cFS_Return_ReturnData_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFS_Return_ReturnData_vec_t;
typedef flatbuffers_uoffset_t *cFS_Return_ReturnData_mutable_vec_t;
#ifndef cFS_Return_Empty_identifier
#define cFS_Return_Empty_identifier flatbuffers_identifier
#endif
#define cFS_Return_Empty_type_hash ((flatbuffers_thash_t)0x26d0422f)
#define cFS_Return_Empty_type_identifier "\x2f\x42\xd0\x26"
#ifndef cFS_Return_UnInt_identifier
#define cFS_Return_UnInt_identifier flatbuffers_identifier
#endif
#define cFS_Return_UnInt_type_hash ((flatbuffers_thash_t)0x95494fba)
#define cFS_Return_UnInt_type_identifier "\xba\x4f\x49\x95"
#ifndef cFS_Return_ReturnData_identifier
#define cFS_Return_ReturnData_identifier flatbuffers_identifier
#endif
#define cFS_Return_ReturnData_type_hash ((flatbuffers_thash_t)0xe603689c)
#define cFS_Return_ReturnData_type_identifier "\x9c\x68\x03\xe6"



struct cFS_Return_Empty_table { uint8_t unused__; };

static inline size_t cFS_Return_Empty_vec_len(cFS_Return_Empty_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_Return_Empty_table_t cFS_Return_Empty_vec_at(cFS_Return_Empty_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_Return_Empty_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_Return_Empty)


struct cFS_Return_UnInt_table { uint8_t unused__; };

static inline size_t cFS_Return_UnInt_vec_len(cFS_Return_UnInt_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_Return_UnInt_table_t cFS_Return_UnInt_vec_at(cFS_Return_UnInt_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_Return_UnInt_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_Return_UnInt)

__flatbuffers_define_scalar_field(0, cFS_Return_UnInt, unsignedInteger, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t cFS_Return_PointerReturn_union_type_t;
__flatbuffers_define_integer_type(cFS_Return_PointerReturn, cFS_Return_PointerReturn_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, cFS_Return_PointerReturn)
#define cFS_Return_PointerReturn_NONE ((cFS_Return_PointerReturn_union_type_t)UINT8_C(0))
#define cFS_Return_PointerReturn_Empty ((cFS_Return_PointerReturn_union_type_t)UINT8_C(1))
#define cFS_Return_PointerReturn_UnInt ((cFS_Return_PointerReturn_union_type_t)UINT8_C(2))

static inline const char *cFS_Return_PointerReturn_type_name(cFS_Return_PointerReturn_union_type_t type)
{
    switch (type) {
    case cFS_Return_PointerReturn_NONE: return "NONE";
    case cFS_Return_PointerReturn_Empty: return "Empty";
    case cFS_Return_PointerReturn_UnInt: return "UnInt";
    default: return "";
    }
}

static inline int cFS_Return_PointerReturn_is_known_type(cFS_Return_PointerReturn_union_type_t type)
{
    switch (type) {
    case cFS_Return_PointerReturn_NONE: return 1;
    case cFS_Return_PointerReturn_Empty: return 1;
    case cFS_Return_PointerReturn_UnInt: return 1;
    default: return 0;
    }
}


struct cFS_Return_ReturnData_table { uint8_t unused__; };

static inline size_t cFS_Return_ReturnData_vec_len(cFS_Return_ReturnData_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFS_Return_ReturnData_table_t cFS_Return_ReturnData_vec_at(cFS_Return_ReturnData_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFS_Return_ReturnData_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFS_Return_ReturnData)

__flatbuffers_define_scalar_field(0, cFS_Return_ReturnData, retval, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_union_field(flatbuffers_, 2, cFS_Return_ReturnData, output, cFS_Return_PointerReturn, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* CFS_RETURN_READER_H */
